"""Check the Earth Engine export of Aguascalientes (April 2024) before it is tiled and labeled.

Usage::

    python scripts/check_ags_raster.py [--boundary data/ref/<file>]

Steps:
    1. Build ``data/ags/raw/s2_ags_2024_04.vrt`` from ``data/ags/raw/s2_ags_2024_04*.tif`` with
       ``gdalbuildvrt`` and assert 14 bands, uint16, EPSG:32613 and 10 m pixels.
    2. Per spectral band, over pixels with ``valid_obs > 0``: p2, median and p98, compared with the
       EuroSAT train mean/std (``configs/stats/eurosat_train_stats.json``).
    3. ``valid_obs`` summary, its distribution over valid pixels, and the pixel offset of the
       first full 640 m cell (the origin only has to be a multiple of the 10 m pixel size).
    4. RGB preview (B04, B03, B02, 2-98 % stretch) in ``docs/figures/ags_2024_04_rgb.png``.

Outputs:
    docs/data_ags_check.md             generated report
    docs/figures/ags_2024_04_rgb.png   downsampled preview

Bands are read one at a time (about 56 M pixels each) to keep memory low. EuroSAT percentiles are
not available (the stats file only holds mean and std), so the comparison uses the z-score of the
Aguascalientes median and the fraction of pixels within mean +/- 3 std; it is a screening heuristic,
not a pass/fail test.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import numpy as np

from hydroscope.geo.gee_export import (
    EXPORT_CRS,
    FILE_PREFIX,
    GRID_M,
    PIXEL_SIZE_M,
    VALID_OBS_BAND,
    eurosat_band_names,
)

HEADER = "<!-- Generated by scripts/check_ags_raster.py. Do not edit by hand. -->"
ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = Path("data/ags/raw")
STATS_PATH = Path("configs/stats/eurosat_train_stats.json")
REPORT_PATH = Path("docs/data_ags_check.md")
PREVIEW_PATH = Path("docs/figures/ags_2024_04_rgb.png")

N_BANDS = 14
RGB_BANDS = ("B04", "B03", "B02")
Z_THRESHOLD = 2.0
WITHIN_STD = 3.0
PERCENTILES = (2.0, 50.0, 98.0)
NO_OBS_WARN_FRACTION = 0.01
PREVIEW_MAX_SIDE = 1600


# --------------------------------------------------------------------------------------------
# Pure statistics
# --------------------------------------------------------------------------------------------


def valid_mask(valid_obs: np.ndarray) -> np.ndarray:
    """Boolean mask of pixels with at least one cloud-free observation."""
    return np.asarray(valid_obs) > 0


def band_percentiles(
    band: np.ndarray, valid: np.ndarray, q: Sequence[float] = PERCENTILES
) -> tuple[float, float, float]:
    """Percentiles ``q`` (default p2, median, p98) of ``band`` over the ``valid`` pixels.

    Returns NaNs if there is no valid pixel.
    """
    values = np.asarray(band)[np.asarray(valid, dtype=bool)]
    if values.size == 0:
        return (float("nan"),) * len(q)  # type: ignore[return-value]
    result = np.percentile(values.astype(np.float32), list(q))
    return tuple(float(v) for v in result)  # type: ignore[return-value]


def zscore(value: float, mean: float, std: float) -> float:
    """``(value - mean) / std``; NaN if ``std`` is not positive."""
    if not std > 0:
        return float("nan")
    return float((value - mean) / std)


def flag_z(z: float, threshold: float = Z_THRESHOLD) -> bool:
    """True if ``|z| > threshold`` (NaN is not flagged)."""
    return bool(abs(z) > threshold)


def fraction_within(
    band: np.ndarray, valid: np.ndarray, mean: float, std: float, k: float = WITHIN_STD
) -> float:
    """Fraction of valid pixels with ``|value - mean| <= k * std``; NaN without valid pixels."""
    values = np.asarray(band)[np.asarray(valid, dtype=bool)]
    if values.size == 0:
        return float("nan")
    return float(np.mean(np.abs(values.astype(np.float64) - mean) <= k * std))


def summarize_valid_obs(valid_obs: np.ndarray, inside: np.ndarray | None = None) -> dict[str, Any]:
    """Summary of the ``valid_obs`` band.

    Args:
        valid_obs: count of cloud-free observations per pixel.
        inside: optional boolean mask of in-state pixels. If ``None`` the state mask is not
            available and ``valid_obs == 0`` is used as a proxy (outside-state pixels and in-state
            pixels without observations cannot be told apart).

    Returns:
        dict with ``min``, ``median``, ``max`` (over in-state pixels, or over all pixels in proxy
        mode), ``n_pixels`` (pixels counted), ``n_zero``, ``fraction_zero`` and ``distinguishable``.
    """
    vo = np.asarray(valid_obs)
    distinguishable = inside is not None
    values = vo[np.asarray(inside, dtype=bool)] if inside is not None else vo.reshape(-1)
    n = int(values.size)
    n_zero = int(np.count_nonzero(values == 0))
    return {
        "min": int(values.min()) if n else None,
        "median": float(np.median(values)) if n else None,
        "max": int(values.max()) if n else None,
        "n_pixels": n,
        "n_zero": n_zero,
        "fraction_zero": (n_zero / n) if n else float("nan"),
        "distinguishable": distinguishable,
    }


def grid_offset_px(
    left: float, top: float, grid: int = GRID_M, pixel: int = PIXEL_SIZE_M
) -> tuple[int, int] | None:
    """Pixel offset ``(col, row)`` of the first full ``grid`` cell from the raster origin.

    The ``grid`` lattice (multiples of ``grid`` metres) falls on pixel boundaries whenever the
    origin is a multiple of the pixel size, even if the raster does not start on the lattice
    (Earth Engine crops the export to the region). Returns ``None`` if the origin is not a
    multiple of ``pixel``, i.e. grid cells would not map to whole pixel windows.
    """
    if left % pixel != 0 or top % pixel != 0:
        return None
    first_x = -(-left // grid) * grid  # first lattice line at or east of the left edge
    first_y = (top // grid) * grid  # first lattice line at or south of the top edge
    return int((first_x - left) // pixel), int((top - first_y) // pixel)


def summarize_valid_pixels(valid_obs: np.ndarray, pixel: int = PIXEL_SIZE_M) -> dict[str, Any]:
    """Distribution of ``valid_obs`` over pixels with at least one cloud-free observation.

    Returns:
        dict with ``min``, ``median``, ``max``, ``area_km2`` (valid pixels x pixel area) and
        ``counts`` (``{valid_obs value: pixel count}`` for every value present), or ``None``
        statistics if no pixel is valid.
    """
    values = np.asarray(valid_obs)
    values = values[values > 0]
    if values.size == 0:
        return {"min": None, "median": None, "max": None, "area_km2": 0.0, "counts": {}}
    counts = np.bincount(values.astype(np.int64))
    return {
        "min": int(values.min()),
        "median": float(np.median(values)),
        "max": int(values.max()),
        "area_km2": float(values.size * pixel * pixel / 1e6),
        "counts": {int(v): int(c) for v, c in enumerate(counts) if c > 0},
    }


def stretch(
    band: np.ndarray, valid: np.ndarray, low: float = 2.0, high: float = 98.0
) -> np.ndarray:
    """Linear stretch of ``band`` to [0, 1] between the percentiles of its valid pixels."""
    values = np.asarray(band, dtype=np.float32)
    mask = np.asarray(valid, dtype=bool)
    if not mask.any():
        return np.zeros(values.shape, dtype=np.float32)
    lo, hi = np.percentile(values[mask], [low, high])
    if hi <= lo:
        return np.zeros(values.shape, dtype=np.float32)
    return np.clip((values - lo) / (hi - lo), 0.0, 1.0).astype(np.float32)


def compare_band(
    band: np.ndarray, valid: np.ndarray, mean: float, std: float, name: str
) -> dict[str, Any]:
    """Statistics of one band over valid pixels and their comparison with EuroSAT mean/std."""
    p2, median, p98 = band_percentiles(band, valid)
    z = zscore(median, mean, std)
    return {
        "band": name,
        "p2": p2,
        "median": median,
        "p98": p98,
        "eurosat_mean": mean,
        "eurosat_std": std,
        "z": z,
        "flag": flag_z(z),
        "within_3std": fraction_within(band, valid, mean, std),
    }


# --------------------------------------------------------------------------------------------
# Report
# --------------------------------------------------------------------------------------------


def _num(value: float, digits: int = 1) -> str:
    return "n/a" if value is None or not np.isfinite(value) else f"{value:.{digits}f}"


def _offset(offset: Sequence[int] | None) -> str:
    return "n/a" if offset is None else f"col {offset[0]}, row {offset[1]}"


def render_report(
    info: Mapping[str, Any],
    rows: Sequence[Mapping[str, Any]],
    obs: Mapping[str, Any],
    warnings: Sequence[str],
    preview_rel: str | None,
) -> str:
    """Render docs/data_ags_check.md.

    Args:
        info: raster properties (``source``, ``n_tiles``, ``width``, ``height``, ``crs``,
            ``pixel_size``, ``dtype``, ``bands``, ``origin_aligned``).
        rows: output of :func:`compare_band`, one per spectral band.
        obs: output of :func:`summarize_valid_obs` plus ``n_valid`` and ``n_total``.
        warnings: human-readable warnings to list.
        preview_rel: relative path of the RGB preview, or ``None``.
    """
    lines = [
        HEADER,
        "",
        "# Aguascalientes raster check (April 2024)",
        "",
        "Sentinel-2 L1C median composite exported by `hydroscope.geo.gee_export`.",
        "",
        "## Raster",
        "",
        f"- Source: `{info['source']}` ({info['n_tiles']} file(s))",
        f"- Size: {info['width']} x {info['height']} px, {info['bands']} bands, `{info['dtype']}`",
        f"- CRS: {info['crs']}, pixel size: {info['pixel_size']} m",
        f"- Pixel lattice compatible with the {GRID_M} m grid (origin a multiple of "
        f"{info['pixel_size']} m): {'yes' if info['origin_aligned'] else 'NO'}",
        f"- First full {GRID_M} m cell at pixel offset: {_offset(info.get('grid_offset_px'))}",
        "",
        "## Band statistics versus EuroSAT train",
        "",
        "Statistics over pixels with `valid_obs > 0`, in digital numbers (reflectance x 10000).",
        "EuroSAT percentiles are not available (only mean and std are stored), so each",
        "Aguascalientes median is compared by its z-score `(median - EuroSAT mean) / EuroSAT std`;",
        f"bands with |z| > {Z_THRESHOLD:g} are flagged. The last column is the fraction of pixels",
        f"within EuroSAT mean +/- {WITHIN_STD:g} std. This is a screening heuristic: EuroSAT",
        "covers other regions and land covers, so a flag asks for a visual check, not a failure.",
        "",
        "| Band | Ags p2 | Ags median | Ags p98 | EuroSAT mean | EuroSAT std | z | Flag | "
        f"Within {WITHIN_STD:g} std |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | :---: | ---: |",
    ]
    for r in rows:
        within = r["within_3std"]
        within_txt = "n/a" if not np.isfinite(within) else f"{100 * within:.1f} %"
        lines.append(
            f"| {r['band']} | {_num(r['p2'])} | {_num(r['median'])} | {_num(r['p98'])} | "
            f"{_num(r['eurosat_mean'])} | {_num(r['eurosat_std'])} | {_num(r['z'], 2)} | "
            f"{'FLAG' if r['flag'] else 'ok'} | {within_txt} |"
        )
    flagged = [r["band"] for r in rows if r["flag"]]
    lines += [
        "",
        f"Flagged bands (|z| > {Z_THRESHOLD:g}): {', '.join(flagged) if flagged else 'none'}.",
        "",
        f"## `{VALID_OBS_BAND}`",
        "",
        "Count of cloud-free observations per pixel (QA60 bits 10 and 11 masked).",
        "",
        f"- Pixels with `{VALID_OBS_BAND}` > 0: {obs['n_valid']} of {obs['n_total']}",
    ]
    if obs["distinguishable"]:
        lines.append(f"- In-state pixels (rasterized boundary): {obs['n_pixels']}")
        scope = "in-state pixels"
    else:
        lines.append(
            "- No boundary given (`--boundary`): outside-state pixels and in-state pixels without "
            "observations are not distinguishable; `valid_obs == 0` is used as a proxy over all "
            "pixels of the raster."
        )
        scope = "all pixels (proxy)"
    lines += [
        f"- min / median / max over {scope}: {obs['min']} / {_num(obs['median'])} / {obs['max']}",
        f"- Pixels with `{VALID_OBS_BAND}` == 0 among {scope}: {obs['n_zero']} "
        f"({100 * obs['fraction_zero']:.2f} %)",
    ]
    valid_px = obs.get("valid_pixels")
    if valid_px is not None:
        lines += [
            f"- Over pixels with `{VALID_OBS_BAND}` > 0: min / median / max = "
            f"{valid_px['min']} / {_num(valid_px['median'])} / {valid_px['max']}; "
            f"area {_num(valid_px['area_km2'])} km2",
            "",
            f"| `{VALID_OBS_BAND}` | Pixels | Share of valid pixels |",
            "| ---: | ---: | ---: |",
        ]
        total = sum(valid_px["counts"].values())
        lines += [f"| {v} | {c} | {100 * c / total:.2f} % |" for v, c in valid_px["counts"].items()]
    lines += [
        "",
        "## Warnings",
        "",
    ]
    lines += [f"- {w}" for w in warnings] if warnings else ["None."]
    lines.append("")
    if preview_rel:
        lines += ["## Preview", "", f"![RGB preview (B04, B03, B02)]({preview_rel})", ""]
    return "\n".join(lines)


def collect_warnings(
    rows: Sequence[Mapping[str, Any]], obs: Mapping[str, Any], info: Mapping[str, Any]
) -> list[str]:
    """Warnings derived from the band comparison, valid_obs summary and raster properties."""
    out = []
    flagged = [r["band"] for r in rows if r["flag"]]
    if flagged:
        out.append(
            f"Bands with |z| > {Z_THRESHOLD:g} versus EuroSAT: {', '.join(flagged)}. "
            "Inspect the preview and the histograms before labeling."
        )
    if obs["fraction_zero"] > NO_OBS_WARN_FRACTION:
        scope = "in-state" if obs["distinguishable"] else "raster"
        out.append(
            f"{100 * obs['fraction_zero']:.2f} % of {scope} pixels have no cloud-free observation."
        )
    if not info["origin_aligned"]:
        out.append(
            f"The raster origin is not a multiple of the {PIXEL_SIZE_M} m pixel size; "
            f"{GRID_M} m grid cells will not fall on whole 64 x 64 pixel windows."
        )
    return out


# --------------------------------------------------------------------------------------------
# I/O
# --------------------------------------------------------------------------------------------


def find_gdalbuildvrt() -> str | None:
    """Locate ``gdalbuildvrt`` on PATH or next to the Python executable (conda env ``bin/``)."""
    found = shutil.which("gdalbuildvrt")
    if found:
        return found
    candidate = Path(sys.executable).parent / "gdalbuildvrt"
    return str(candidate) if candidate.exists() else None


def build_vrt(tifs: Sequence[Path], vrt_path: Path) -> Path:
    """Build a VRT mosaic of ``tifs`` with ``gdalbuildvrt``.

    Raises:
        RuntimeError: if ``gdalbuildvrt`` is not found or fails.
    """
    exe = find_gdalbuildvrt()
    if exe is None:
        raise RuntimeError(
            "gdalbuildvrt not found on PATH or next to the Python executable. Install GDAL "
            "(conda install -c conda-forge gdal) or add its bin/ directory to PATH."
        )
    vrt_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [exe, "-overwrite", str(vrt_path), *map(str, sorted(tifs))]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"gdalbuildvrt failed: {proc.stderr.strip()}")
    return vrt_path


def check_raster_properties(src: Any) -> dict[str, Any]:
    """Validate an open rasterio dataset: 14 bands, uint16, EPSG:32613, 10 m pixels.

    Returns:
        dict of raster properties used by the report.

    Raises:
        ValueError: with a message naming the first violated property.
    """
    if src.count != N_BANDS:
        raise ValueError(f"expected {N_BANDS} bands, found {src.count}")
    dtypes = set(src.dtypes)
    if dtypes != {"uint16"}:
        raise ValueError(f"expected dtype uint16, found {sorted(dtypes)}")
    epsg = src.crs.to_epsg() if src.crs else None
    if f"EPSG:{epsg}" != EXPORT_CRS:
        raise ValueError(f"expected CRS {EXPORT_CRS}, found {src.crs}")
    xres, yres = (abs(r) for r in src.res)
    if not (np.isclose(xres, PIXEL_SIZE_M) and np.isclose(yres, PIXEL_SIZE_M)):
        raise ValueError(f"expected {PIXEL_SIZE_M} m pixels, found {src.res}")
    left, top = src.transform.c, src.transform.f
    return {
        "width": src.width,
        "height": src.height,
        "bands": src.count,
        "dtype": "uint16",
        "crs": EXPORT_CRS,
        "pixel_size": PIXEL_SIZE_M,
        "origin_aligned": grid_offset_px(left, top) is not None,
        "grid_offset_px": grid_offset_px(left, top),
    }


def check_vrt_properties(path: Path) -> dict[str, Any]:
    """Open ``path`` with rasterio and run :func:`check_raster_properties`."""
    import rasterio

    with rasterio.open(path) as src:
        return check_raster_properties(src)


def load_eurosat_stats(path: Path) -> dict[str, dict[str, float]]:
    """Load EuroSAT per-band mean/std; raises ``FileNotFoundError`` with a hint if missing."""
    if not path.exists():
        raise FileNotFoundError(
            f"EuroSAT statistics not found: {path}. Run `python scripts/prepare_eurosat.py` first."
        )
    stats = json.loads(path.read_text())
    missing = [b for b in eurosat_band_names() if b not in stats]
    if missing:
        raise ValueError(f"{path} lacks bands {missing}")
    return stats


def rasterize_boundary(boundary: Path, src: Any) -> np.ndarray:
    """Boolean in-state mask on the grid of ``src``, rasterized from a vector file."""
    import geopandas as gpd
    from rasterio.features import rasterize

    gdf = gpd.read_file(boundary).to_crs(src.crs)
    shapes = [(geom, 1) for geom in gdf.geometry if geom is not None and not geom.is_empty]
    mask = rasterize(
        shapes, out_shape=(src.height, src.width), transform=src.transform, dtype="uint8"
    )
    return mask.astype(bool)


def write_preview(src: Any, path: Path, max_side: int = PREVIEW_MAX_SIDE) -> None:
    """Write the RGB preview (B04, B03, B02; 2-98 % stretch per band) as a PNG.

    The image is read downsampled with ``out_shape`` and nearest-neighbour resampling, so edge
    pixels are not darkened by blending with zeros. Pixels without observation are transparent.
    """
    import matplotlib.image as mpimg
    from rasterio.enums import Resampling

    scale = min(1.0, max_side / max(src.width, src.height))
    shape = (max(1, round(src.height * scale)), max(1, round(src.width * scale)))
    names = eurosat_band_names()
    idx = [names.index(b) + 1 for b in RGB_BANDS]
    data = src.read(idx, out_shape=(len(idx), *shape), resampling=Resampling.nearest)
    valid = src.read(N_BANDS, out_shape=shape, resampling=Resampling.nearest) > 0
    rgb = np.stack([stretch(data[i], valid) for i in range(len(idx))], axis=-1)
    rgba = np.concatenate([rgb, valid[..., None].astype(np.float32)], axis=-1)
    path.parent.mkdir(parents=True, exist_ok=True)
    mpimg.imsave(path, rgba)


def _display_path(path: Path) -> str:
    """``path`` relative to the repository root when possible (no user-specific prefix)."""
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def run_check(
    raw_dir: Path,
    stats_path: Path,
    report_path: Path,
    preview_path: Path,
    boundary: Path | None = None,
    vrt_path: Path | None = None,
) -> dict[str, Any]:
    """Run the whole check and write the report and the preview.

    Raises:
        FileNotFoundError: if the EuroSAT statistics or the raw tiles are missing.
        ValueError: if the raster properties are wrong.
        RuntimeError: if the VRT cannot be built.
    """
    import rasterio

    stats = load_eurosat_stats(stats_path)
    tifs = sorted(raw_dir.glob(f"{FILE_PREFIX}*.tif"))
    if not tifs:
        raise FileNotFoundError(
            f"no files matching {raw_dir / (FILE_PREFIX + '*.tif')}; download the Drive export "
            "first."
        )
    vrt_path = vrt_path or raw_dir / f"{FILE_PREFIX}.vrt"
    build_vrt(tifs, vrt_path)

    names = eurosat_band_names()
    with rasterio.open(vrt_path) as src:
        info = check_raster_properties(src)
        info["source"] = _display_path(vrt_path)
        info["n_tiles"] = len(tifs)

        valid_obs = src.read(N_BANDS)
        valid = valid_mask(valid_obs)
        inside = rasterize_boundary(boundary, src) if boundary is not None else None
        obs = summarize_valid_obs(valid_obs, inside)
        obs["n_valid"] = int(valid.sum())
        obs["n_total"] = int(valid.size)
        obs["valid_pixels"] = summarize_valid_pixels(valid_obs)
        del valid_obs

        rows = []
        for i, name in enumerate(names, start=1):
            band = src.read(i)  # one band at a time
            rows.append(compare_band(band, valid, stats[name]["mean"], stats[name]["std"], name))
            del band

        write_preview(src, preview_path)

    warnings = collect_warnings(rows, obs, info)
    try:
        preview_rel = str(preview_path.relative_to(report_path.parent))
    except ValueError:
        preview_rel = str(preview_path)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(render_report(info, rows, obs, warnings, preview_rel))
    return {"info": info, "rows": rows, "obs": obs, "warnings": warnings}


def main(argv: Sequence[str] | None = None) -> int:
    """Command-line entry point; returns the process exit code."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--boundary",
        type=Path,
        default=None,
        help="state boundary file (e.g. data/ref/<file>.gpkg) to separate outside-state pixels",
    )
    parser.add_argument("--raw-dir", type=Path, default=ROOT / RAW_DIR)
    parser.add_argument("--stats", type=Path, default=ROOT / STATS_PATH)
    parser.add_argument("--report", type=Path, default=ROOT / REPORT_PATH)
    parser.add_argument("--preview", type=Path, default=ROOT / PREVIEW_PATH)
    args = parser.parse_args(argv)
    try:
        result = run_check(
            args.raw_dir, args.stats, args.report, args.preview, boundary=args.boundary
        )
    except (FileNotFoundError, ValueError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print(f"Wrote {args.report} and {args.preview}")
    for w in result["warnings"]:
        print(f"WARNING: {w}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
