"""Download EuroSAT MS, cache it as .npy, compute train-only band statistics and the data card.

Usage (downloads ~2 GB, writes a ~2.9 GB cache)::

    python scripts/prepare_eurosat.py [--force]

Outputs:
    data/eurosat/cache/{train,val,test}_{x,y}.npy   uint16 cache (git-ignored)
    configs/stats/eurosat_train_stats.json          per-band mean/std from EuroSAT train only
    docs/data_eurosat.md                            class x split counts, totals, band order
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import numpy as np
from torchgeo.datasets import EuroSAT

from hydroscope.data.eurosat import (
    BAND_SETS,
    CLASSES,
    SPLITS,
    cache_paths,
    save_band_stats,
    train_band_stats,
    write_split_cache,
)

EXPECTED_TOTAL = 27_000
HEADER = "<!-- Generated by scripts/prepare_eurosat.py. Do not edit by hand. -->"

logger = logging.getLogger("prepare_eurosat")


def render_data_card(
    counts: dict[str, np.ndarray],
    classes: tuple[str, ...],
    band_names: tuple[str, ...],
    stats: dict[str, dict[str, float]],
) -> str:
    """Render docs/data_eurosat.md.

    Args:
        counts: per split, the number of patches of each class (class index order).
        classes: class names in index order.
        band_names: band names in input order.
        stats: train-only per-band statistics keyed by band name.
    """
    splits = list(counts)
    lines = [
        HEADER,
        "",
        "# EuroSAT data card",
        "",
        "EuroSAT MS from TorchGeo with its official train/val/test split.",
        "Patches are 13 x 64 x 64, stored as `uint16` digital numbers.",
        "",
        "## Patches per class and split",
        "",
        "| Index | Class | " + " | ".join(splits) + " | total |",
        "| --- | --- | " + " | ".join("---:" for _ in splits) + " | ---: |",
    ]
    for i, name in enumerate(classes):
        row = [int(counts[s][i]) for s in splits]
        lines.append(f"| {i} | {name} | " + " | ".join(map(str, row)) + f" | {sum(row)} |")
    split_totals = [int(counts[s].sum()) for s in splits]
    lines.append(
        "| | **Total** | " + " | ".join(map(str, split_totals)) + f" | {sum(split_totals)} |"
    )
    lines += [
        "",
        "## Bands",
        "",
        "Order is TorchGeo's (B8A last). Statistics are computed on the train split only, over all",
        "pixels, in raw digital numbers (population std).",
        "",
        "| Index | Band | Mean | Std |",
        "| --- | --- | ---: | ---: |",
    ]
    for i, band in enumerate(band_names):
        lines.append(f"| {i} | {band} | {stats[band]['mean']:.4f} | {stats[band]['std']:.4f} |")
    lines += [
        "",
        "RGB input = " + ", ".join(BAND_SETS["rgb"]) + " (taken from the same files).",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Run the full preparation pipeline."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default="data/eurosat")
    parser.add_argument("--cache-dir", default=None, help="default: {root}/cache")
    parser.add_argument("--stats-out", default="configs/stats/eurosat_train_stats.json")
    parser.add_argument("--doc-out", default="docs/data_eurosat.md")
    parser.add_argument("--force", action="store_true", help="rewrite existing caches")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    root = Path(args.root)
    cache_dir = Path(args.cache_dir) if args.cache_dir else root / "cache"

    for split in SPLITS:
        x_path, y_path = cache_paths(cache_dir, split)
        if x_path.exists() and y_path.exists() and not args.force:
            logger.info("%s: cache exists, skipping (use --force to rewrite)", split)
            continue
        logger.info("%s: writing cache", split)
        write_split_cache(split, root, cache_dir)

    # Checks: classes, bands, sizes.
    assert len(CLASSES) == 10, f"expected 10 classes, got {len(CLASSES)}"
    assert list(EuroSAT(root, "train", download=True).classes) == list(CLASSES)
    band_names = BAND_SETS["ms13"]
    assert len(band_names) == 13 and band_names[-1] == "B8A", band_names
    counts: dict[str, np.ndarray] = {}
    for split in SPLITS:
        x_path, y_path = cache_paths(cache_dir, split)
        x = np.load(x_path, mmap_mode="r")
        y = np.load(y_path)
        assert x.shape[1:] == (13, 64, 64) and len(x) == len(y), (split, x.shape, y.shape)
        assert y.max() < len(CLASSES), f"{split}: label out of range"
        counts[split] = np.bincount(y, minlength=len(CLASSES))
    total = sum(int(c.sum()) for c in counts.values())
    assert total == EXPECTED_TOTAL, f"expected {EXPECTED_TOTAL} patches in total, got {total}"
    assert all((c > 0).all() for c in counts.values()), "a class is missing from a split"

    stats = train_band_stats(cache_dir)
    save_band_stats(stats, args.stats_out)
    logger.info("wrote %s", args.stats_out)

    doc = Path(args.doc_out)
    doc.parent.mkdir(parents=True, exist_ok=True)
    doc.write_text(render_data_card(counts, CLASSES, band_names, stats))
    logger.info("wrote %s", doc)


if __name__ == "__main__":
    main()
